2022-03-15 13:31:51,940 INFO this is the start of my code and I am trying to enter 4 and 5
2022-03-15 13:31:51,941 INFO executed successfully
2022-03-15 13:31:52,310 INFO this is the start of my code and I am trying to enter 4 and 0
2022-03-15 13:31:52,311 ERROR error has happeneddivision by zero
2022-03-15 13:31:52,311 ERROR exception occured
Traceback (most recent call last):
  File "C:\Users\ROKAYA~1\AppData\Local\Temp/ipykernel_12796/150142832.py", line 4, in divbyzero
    div = a/b
ZeroDivisionError: division by zero
2022-03-21 14:00:21,461 INFO this is the start of my code and I am trying to enter 4 and 5
2022-03-21 14:00:21,485 INFO executed successfully
2022-03-21 14:00:22,040 INFO this is the start of my code and I am trying to enter 4 and 0
2022-03-21 14:00:22,048 ERROR error has happeneddivision by zero
2022-03-21 14:00:22,048 ERROR exception occured
Traceback (most recent call last):
  File "C:\Users\ROKAYA~1\AppData\Local\Temp/ipykernel_5336/150142832.py", line 4, in divbyzero
    div = a/b
ZeroDivisionError: division by zero
